apiVersion: quintoandar.com.br/checklist/v2
kind: ServiceChecklist

metadata:
  name: ec2-github-runner
spec:
  description: >-
    A Github Workflow used to create a EC2 instance with a Github Runner.
  costCenter: C058
  department: infra
  lifecycle: production

  ownership:
    line: tech_platform
    tribe: cloud_platform
    squad: platform_business
    owner: cleber.ferreira@quintoandar.com.br

  channels:
    squad:  '#platform-business'
    alerts: '#alerts-platform'
